# Generated by Django 2.2.1 on 2019-06-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('team1', models.CharField(max_length=64)),
                ('team2', models.CharField(max_length=64)),
                ('toss_winner', models.CharField(max_length=64)),
                ('toss_decision', models.BooleanField()),
                ('result', models.CharField(max_length=10)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(max_length=64)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_the_match', models.CharField(max_length=64)),
                ('venue', models.CharField(max_length=64)),
                ('umpire1', models.CharField(max_length=64)),
                ('umpire2', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('batting_team', models.CharField(max_length=64)),
                ('bowling_team', models.CharField(max_length=64)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=64)),
                ('non_striker', models.CharField(max_length=64)),
                ('bowler', models.CharField(max_length=64)),
                ('is_super_over', models.BooleanField(default=0)),
                ('wide_runs', models.IntegerField(default=0)),
                ('bye_runs', models.IntegerField(default=0)),
                ('legbye_run', models.IntegerField(default=0)),
                ('noball_runs', models.IntegerField(default=0)),
                ('penalty_runs', models.IntegerField(default=0)),
                ('batsman_runs', models.IntegerField(default=0)),
                ('extra_runs', models.IntegerField(default=0)),
                ('totals', models.IntegerField(default=0)),
                ('player_dismissed', models.CharField(blank=True, max_length=64, null=True)),
                ('dismisal_kind', models.CharField(blank=True, max_length=16, null=True)),
                ('fielder', models.CharField(blank=True, max_length=16, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplfreak.Match')),
            ],
        ),
    ]
