# Generated by Django 2.2.1 on 2019-06-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplfreak', '0002_auto_20190617_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='umpire1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
