# Generated by Django 2.2.1 on 2019-06-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplfreak', '0003_auto_20190617_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
