# Generated by Django 2.2.1 on 2019-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplfreak', '0005_auto_20190617_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='dismisal_kind',
            new_name='dismissal_kind',
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='batsman',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='batting_team',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bowler',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bowling_team',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='non_striker',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
